language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master

    #netlify token for cheeseHub 346026ec40fa605f89aab03fe32422a2c77b23c749a266cfdaa79f7748cb9c21